# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.7.0
  heroku: circleci/heroku@1.2.6
  mailer-orb: sudiptog81/mailer-orb@1.0.0

jobs:
  build: 

#jobs:
#  run:
#    executor: node/default
#    steps:
#      - checkout
#      - node/install-packages:
#          cache-path: ~/project/node_modules
#          override-ci-command: npm i
#      - run: npm start


#name of orbs/jobs to run
workflows:
  matrix-tests:
    jobs:
      - node/test:    
          version: 13.11.0
      - node/test:
          version: 12.16.0
      - node/test:
          version: 10.19.0
      - mailer-orb/mail:
          body: |-
            Sample Mail
            Regards,
            Circle CI
          from: nguyenminhtam1106999@gmail.com
          subject: Example mail from mailer-orb
          to: nt11061999@gmail.com, nguyenminhtam1106999@gmail.com
          requires:
            - node/test