version: 2.1

orbs:
  node: circleci/node@4.7.0
  heroku: circleci/heroku@1.2.6

jobs:
  install-and-test:
   executor: node/default
   steps:
     - checkout
     - node/install-packages:
         cache-path: ~/project/node_modules
         override-ci-command: npm i
     - run: npm test

workflows:
  matrix-tests:
    jobs:
      - install-and-test

