version: 2.1

orbs:
  node: circleci/node@4.7.0
  heroku: circleci/heroku@1.2.6

jobs:
  install-and-test:
   executor: node/default
   steps:
     - checkout
     - node/install-packages:
         cache-path: ~/project/node_modules
         override-ci-command: npm i
     - run: npm test
deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          command: git add .
          command: git commit -m "deploy to server"
          command: git push heroku master
      - heroku/deploy-via-git
workflows:
  heroku-deployment:
    jobs:
      deploy


